### ISSUE TITLE
Https-ссылки в письмах и цвет текста ссылки при переходе в Outlook

### ISSUE THREAD

**Issue by Sogl** [dudeonthehorse/Email#12]
Приветствую!

Набросал шаблон на основе фреймворка убрав все лишнее оформление и обнаружил интересный баг, который довольно сложно отлавливается, а именно: 
- Если у нас в письме имеется ссылка вида `https://foo.bar.com`
- Если у нас в письме есть определенное ФИО вида `Лаузер П. С.`
- И все это находится в шаблоне по типу `mainTemplate`

То ссылка превращается в такую: `https://foo.barcom`, т е удаляется вторая точка, из-за чего переход по ней ни к чему не приводит. В моем случае срабатывает 100%-но только с определенными фамилиями в шаблоне и только с моей ссылкой. Письма отправляю по протоколу SMTP через корпоративный Exchange-сервер. При отправке на личный ящик gmail происходит такая же ерунда, значит дело не в Outlook.

Пока что нашел workaround - это использование `http` вместо `https` и редирект через `apache/htaccess`, однако сама проблема выглядит довольно странно.
У Вас большой опыт в верстке писем. Может, сталкивались с чем-то подобным?

По второму вопросу. Решил изменить цвет кнопки `Try Inliner` с черного на зеленый. 
Поменял стили:

``` css
.button-link {
    ...
    background-color: #6fb58d;
    border: #6fb58d 10px solid;
    ...
}
```

Теперь при переходе из Outlook 2010 цвет ссылки становится фиолетовым.
До перехода:
![image](https://cloud.githubusercontent.com/assets/7556290/10567668/e96ecd8e-764d-11e5-856c-1ea22f3e9d27.png)

После перехода:
![image](https://cloud.githubusercontent.com/assets/7556290/10567653/94e78954-764d-11e5-9aa5-577e81491f1a.png)

Такой проблемы нет со стандартной кнопкой.
Как можно решить данную проблемку?

**Comment by dudeonthehorse** [comment]
Привет.

Проблема битым адресом ссылки действительно странная, но я не использую https ссылки в письмах. Редирект с http на https вполне себе удачное решение, которое используется большинством вменяемых сайтов.

Относительно цвета ссылки-кнопки: !important цвет ссылки присутствует?

**Comment by Sogl** [comment]
> Относительно цвета ссылки-кнопки: !important цвет ссылки присутствует?

Все `!important` в сгенерированном файле присутствуют в `<head>` секции. Конкретно по этой ссылке:

``` css
.button-link{font-family:helvetica;font-size:14px;color:#fff!important;font-weight:700;text-decoration:none;background-color:#6fb58d;border:#6fb58d 10px solid;padding:0 10px;border-radius:25px;display:inline-block}
.button-link span{color:#fff}
```

При попытке добавить `!important` еще в `span`:

``` css
.button-link span{color:#fff!important}
```

ничего не изменилось.

Более того, при сохранении полученного письма в html-формате и просмотре инспектором Chrome, видно, что стили из `head` не применяются:
![image](https://cloud.githubusercontent.com/assets/7556290/10568142/61b13404-7657-11e5-9bd3-1f96463c813f.png)

Затем внес стили инлайн в `span`:

``` html
<span style="color:#fff !important">Войти в ПУЛЬС</span>
```

При сохранении письма в html:
![image](https://cloud.githubusercontent.com/assets/7556290/10568170/cb094ec8-7657-11e5-807f-0067973f00e8.png)

По идее, все должно уже работать. 
Однако, ссылка снова срабатывает фиолетовым цветом.

**Comment by dudeonthehorse** [comment]
В принципе все должно работать если в инлайне будет присутствовать запись color:#ffffff !important; для самой ссылки. Но сейчас этого не происходит. Дело в gulp инлайнере. Вопрос решается с разработчиком инлайнера. Плюс проведу пару тестов на неделе. Вопрос остается открытым. Тему не закрываю.

**Comment by Sogl** [comment]
Первая проблема куда-то пропала после замены одного слова в шаблоне. Вернул обратно - тоже работает. Мистика прям :confused: 

При возврате цвета кнопки "как было":

``` css
.button-link {
    ...
    background-color: #333333;
    border: #333333 10px solid;
    ...
}
```

2-я проблема пропадает.

Смотрим в инспектор:
![image](https://cloud.githubusercontent.com/assets/7556290/10568350/465f2474-765a-11e5-9d5f-dbace894a055.png)

Не вижу разницы с применением другого цвета.

> В принципе все должно работать если в инлайне будет присутствовать запись color:#ffffff !important; для самой ссылки. 

Не хочет работать, даже если к ссылке и span'у добавить.

**Comment by dudeonthehorse** [comment]
Будет решено в релизной версии

**Comment by tegscramp** [comment]
Outlook меняет цвет на ссылки по которым уже переходили.
a:visited{color:#fff;}
это должно профиксить баг.
span не надо добавлять.

**Comment by tegscramp** [comment]
Причем фиолетовый или другой цвет, по моему, меняется в настройках винды, если я ничего не путаю.

**Comment by dudeonthehorse** [comment]
Span необходим в случае разноцветных ссылок в письме.

**Comment by Sogl** [comment]
@dudeonthehorse Проблема с цветом посещенной ссылки в Outlook осталась в последней версии вашего фреймворка.
Пробовал внести в `base.less`:
```css
.button-link:visited {
  color: #ffffff;
}
```
и не увидел вообще псевдоклассов в сгенерированном билде html.

Далее нашел, что, похоже, Outlook вообще не поддерживает псевдоклассы:
https://www.campaignmonitor.com/forums/topic/7303/visited-links-in-outlook-2010-and-probably-2007/

И вот есть вероятное решение, которое кому-то помогло:
https://litmus.com/community/discussions/4164-outlook-07-13-visited-link-color-fix

**Comment by dudeonthehorse** [comment]
```.button-link { color:#ffffff !important; }``` в инлайне не решает вопрос?

**Comment by Sogl** [comment]
Нет, не решает. Он стоит там по умолчанию, я сейчас посмотрел.

**Comment by dudeonthehorse** [comment]
https://litmus.com/community/discussions/4164-outlook-07-13-visited-link-color-fix

**Comment by Sogl** [comment]
Я выше дал ссылку на это :wink: 
Мне только `mso-style-priority:99;` нужен? Цвет то у нас конкретный задан.

**Comment by Sogl** [comment]
Вот так пробовал внести в стили:
```css
a.button-link {
    mso-style-priority:99;
    color:inherit;
}
a.button-link span {
    mso-style-priority:99;
    color:inherit;
}
```

Потом так:
```html
<a class="button-link" href="https://mylink/" target="_blank" style="background-color: #6fb58d; 
border: #6fb58d 10px solid; border-radius: 25px; color: #ffffff !important; display: inline-block; 
font-family: helvetica; font-size: 14px; font-weight: bold; padding: 0 10px; 
text-decoration: none;mso-style-priority:99;">
    <span style="color: #ffffff;mso-style-priority:99;">Войти в ПУЛЬС</span>
</a>
```

Не помогает.
