### ISSUE TITLE
Странности в css

### ISSUE THREAD

**Issue by byashimov** [dudeonthehorse/Email#18]
Верстка хтмл писем -- ад адовый, поэтому я не уверен, то ли это тщательно подобранные хаки для разных почтовых клиентов, то ли просто случайности, поправьте, пожалуйста, или откомментируйте, если "так надо". Спасибо.

``` css
.cover img {
    width: 100%;
    /* 1 */
    height: auto;
    max-width: 600px;
    /* 2 */
    height: auto;
    display: block;
    border-radius: 4px 4px 0 0;
}
p {
    /* Capital */
    Margin: 1em 0;
}
```
